config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }


  root 'items#index'

  get '/users/entrance', to: 'users#entrance', as: 'entrance'

  resources :address, only: [:index, :new, :edit, :update]
  resources :credit, only: [:index, :new, :edit, :update]

  resources :items do
      get 'buy'
      get 'buy_page'
      get 'buy_done'
      get 'buy_done'
      post 'create_review'
  end

  resources :users, only: [:create, :edit, :update, :delete, :show]  do
    get 'complete'
    get 'my_list'
    get 'transaction_list'
    get 'sell_end_list'
    get 'open_trade'
    get 'trading_performance'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one  :area
  has_many :items
  has_many :reviews
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  def after_sign_up_path_for(resource)
    new_address_path
  end

  def after_inactive_sign_up_path_for(resource)
    new_address_path
  end
  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
   @user = current_user
   @items = current_user.items
   @reviews = Review.where(user_id: current_user.id)
  end

  def create
  end

  def edit
  end

  def update
  end

  def entrance
  end

  #初回ユーザー登録
  def complete
   @user = current_user
  end

  def my_list
   @user = current_user
   #出品中itemsのみビューに渡す。
   @items = current_user.items.order("created_at DESC").select {|item| item.status == "出品中"}
  end

  def transaction_list
   @user = current_user
  end

  def sell_end_list
   @user = current_user
   #取引完了itemsのみビューに渡す。
   @items = current_user.items.order("created_at DESC").select {|item| item.status == "取引完了"}
  end

  def open_trade
   @user = current_user
  end

  def trading_performance
   @user = current_user
   @items = Item.all.select {|item| item.buyer_id == current_user.id}
  end

  private

  def user_params
    params.require(:user).permit(
      :nickname,
      :email,
      :last_name,
      :first_name,
      :last_kananame,
      :first_kananame,
      :post_number,
      :city,
      :address,
      :building,
      :phone_number,
      :card_number,
      :expiration_year,
      :expiration_month,
      :security_code,
      :user_photo,
      :total_money,
      :review_id,
      :area_id)
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_footer.html.haml
%footer.single-footer
  %nav
    %ul
      %li
        %a{ href: 'https://www.mercari.com/jp/privacy/'}
          プライバシーポリシー
      %li
        %a{ href: 'https://www.mercari.com/jp/tos/'}
          利用規約
      %li
        %a{ href: 'https://www.mercari.com/jp/tokutei/'}
          特定商取引に関する表記
  = link_to root_path, {class: "footer-logo"} do
    = image_tag("logo-gray.svg", class: "footer-logo-gray")
  %p
    © 2017 Mercari

app/views/users/complete.html.haml
%body
  .single-container
    %header.single-header
      %h1
        = link_to root_path, {class: "header-logo"} do
          = image_tag("logo.svg", class: "top-logo")
        %nav.clearfix
          = image_tag("user-complete.jpg", class: "right-image")
    %main.single-main
      %section.single-contents
        %h2.single-head
          会員登録完了
        .single-inner
          .single-content
            %p
              ありがとうございます。会員登録が完了しました。
            = link_to "メルカリをはじめる","/users/current_user.id",method: :get, class: "btn-default btn-red"
      = image_tag("banner-pc.jpg", class: "pcbanner-image")
    = render 'users/footer'

app/views/users/entrance.html.haml
%body
  .single-container
    %header.single-header
      %h1
        %a{ href: 'https://www.mercari.com/jp/', class: "header-logo"}
          = image_tag("logo.svg", class: "top-logo")
    %main.single-main
      %section.single-contents
        %h2.single-head
          新規会員登録
        .single-inner
          .single-content
            %button#facebook-login.sns-facebook.btn-default
              %i.icon-facebook
              Facebookで登録
            %button#google-login.sns-google.btn-default.btn-red
              %i.icon-google
              Googleで登録
            = link_to "メールアドレスで登録",new_user_registration_path, class: "sns-mail btn-default"
    = render 'footer'

app/views/users/my_list.html.haml
.default-container
  %header.morcari-header
    = render 'items/top_header'
  %nav.bread-crumbs
    %ul
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        = link_to "メルカリ", root_path, {itemprop: "url"}
        %i.fa.fa-chevron-right
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        = link_to "マイページ", "/users/#{current_user.id}" , {itemprop: "title"}
        %i.fa.fa-chevron-right
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        %span{itemprop: "title"}
          出品した商品 - 出品中
  %main.mypage-container.clearfix
    .mypage-content
      %section.mypage-tab__container
        %h2.mypage-tab__head#selling-title
          出品した商品
        %ul.mypages-tabs
          %li#selling-tab
            %h3
              = link_to "出品中", user_my_list_path(@user)
          %li#selling-tab
            %h3#non-active
              = link_to "取引中", user_transaction_list_path
          %li#selling-tab
            %h3#non-active
              = link_to "売却済み", user_sell_end_list_path
        .tab-content
          - if @items.present?
            - @items.each do |item|
              %ul.mypage-item__list#mypage-tab__transaction
                %li.mypage-item__listbox#selling-box
                  = link_to "/items/#{item.id}",class: "mypage-item__link", id: "link-box" do
                    %figure
                      = image_tag item.images.first.image.url
                    .mypage-list__body
                      .mypage-list__text
                        = item.name
                      %div
                        %span.lisiting-item__count
                          %i.fa.fa-heart-o
                          %span
                            0
                        %span.lisiting-item__count
                          %i.fa.fa-comment-o
                          %span
                            0
                        .mypage-item__status
                          = item.status
                    %i.fa.fa-chevron-right
          - else
            .tab-content
              %ul.mypage-item__list#mypage-tab__transaction
                %li.mypage-item__listbox#selling-box
                  .mypage-list__body
                    .mypage-list__text
                    %div#non-exist-item
                      取引中の商品はありません
    .mypage-side
      = render "users/mypage/mypage_sidebar"
  %div.morcari-app__banner
    = image_tag("app-banner.jpg", class: "app-image")
  %footer.morcari-footer
    = render 'items/top_footer'

app/views/users/open_trade.html.haml
.default-container
  %header.morcari-header
    = render 'items/top_header'
  %nav.bread-crumbs
    %ul
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        = link_to "メルカリ", root_path, {itemprop: "url"}
        %i.fa.fa-chevron-right
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        = link_to "マイページ", "/users/#{current_user.id}" , {itemprop: "title"}
        %i.fa.fa-chevron-right
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        %span{itemprop: "title"}
          購入した商品 - 取引中
  %main.mypage-container.clearfix
    .mypage-content
      %section.mypage-tab__container
        %h2.mypage-tab__head#selling-title
          購入した商品
        %ul.mypages-tabs
          %li
            %h3
              = link_to "取引中", user_transaction_list_path(@user)
          %li
            %h3#non-active
              = link_to "過去の取引", user_trading_performance_path(@user)
        .tab-content
          %ul.mypage-item__list#mypage-tab__transaction
            %li.mypage-item__listbox#selling-box
              .mypage-list__body
                .mypage-list__text
                %div#non-exist-item
                  取引中の商品はありません
    .mypage-side
      = render "users/mypage/mypage_sidebar"
  %div.morcari-app__banner
    = image_tag("app-banner.jpg", class: "app-image")
  %footer.morcari-footer
    = render 'items/top_footer'

app/views/users/sell_end_list.html.haml
.default-container
  %header.morcari-header
    = render 'items/top_header'
  %nav.bread-crumbs
    %ul
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        = link_to "メルカリ", root_path, {itemprop: "url"}
        %i.fa.fa-chevron-right
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        = link_to "マイページ", "/users/#{current_user.id}" , {itemprop: "title"}
        %i.fa.fa-chevron-right
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        %span{itemprop: "title"}
          出品した商品 - 売却中
  %main.mypage-container.clearfix
    .mypage-content
      %section.mypage-tab__container
        %h2.mypage-tab__head#selling-title
          出品した商品
        %ul.mypages-tabs
          %li#selling-tab
            %h3#non-active
              = link_to "出品中", user_my_list_path(@user)
          %li#selling-tab
            %h3#non-active
              = link_to "取引中", user_transaction_list_path(@user)
          %li#selling-tab
            %h3
              = link_to "売却済み", user_sell_end_list_path(@user)
        .tab-content
          - if @items.present?
            - @items.each do |item|
              %ul.mypage-item__list#mypage-tab__transaction
                %li.mypage-item__listbox#selling-box
                  = link_to "/items/#{item.id}",class: "mypage-item__link", id: "link-box" do
                    %figure
                      = image_tag item.images.first.image.url
                    .mypage-list__body
                      .mypage-list__text
                        = item.name
                      %div
                        %span.lisiting-item__count
                          %i.fa.fa-heart-o
                          %span
                            0
                        %span.lisiting-item__count
                          %i.fa.fa-comment-o
                          %span
                            0
                        .mypage-item__status#sell-done
                          売却済
                    %i.fa.fa-chevron-right
          - else
            .tab-content
              %ul.mypage-item__list#mypage-tab__transaction
                %li.mypage-item__listbox#selling-box
                  .mypage-list__body
                    .mypage-list__text
                    %div#non-exist-item
                      取引中の商品はありません
    .mypage-side
      = render "users/mypage/mypage_sidebar"
  %div.morcari-app__banner
    = image_tag("app-banner.jpg", class: "app-image")
  %footer.morcari-footer
    = render 'items/top_footer'

app/views/users/show.html.haml
.default-container
  %header.morcari-header
    = render 'items/top_header'
  %nav.bread-crumbs
    %ul
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        = link_to "メルカリ", root_path, {itemprop: "url"}
        %i.fa.fa-chevron-right
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        %span{itemprop: "title"}
          マイページ
  %main.mypage-container.clearfix
    = render 'users/mypage/mypage_main'
    .mypage-side
      = render "users/mypage/mypage_sidebar"
  %div.morcari-app__banner
    = image_tag("app-banner.jpg", class: "app-image")
  %footer.morcari-footer
    = render 'items/top_footer'

app/views/users/trading_performance.html.haml
.default-container
  %header.morcari-header
    = render 'items/top_header'
  %nav.bread-crumbs
    %ul
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        = link_to "メルカリ", root_path, {itemprop: "url"}
        %i.fa.fa-chevron-right
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        = link_to "マイページ", "/users/#{current_user.id}" , {itemprop: "title"}
        %i.fa.fa-chevron-right
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        %span{itemprop: "title"}
          購入した商品 - 過去の取引
  %main.mypage-container.clearfix
    .mypage-content
      %section.mypage-tab__container
        %h2.mypage-tab__head#selling-title
          購入した商品
        %ul.mypages-tabs
          %li
            %h3#non-active
              = link_to "取引中", user_open_trade_path(@user)
          %li
            %h3
              = link_to "過去の取引", user_trading_performance_path(@user)
        .tab-content
          - if @items.present?
            - @items.each do |item|
              %ul.mypage-item__list#mypage-tab__transaction
                %li.mypage-item__listbox#selling-box
                  = link_to "/items/#{item.id}",class: "mypage-item__link", id: "link-box" do
                    %figure
                      = image_tag item.images.first.image.url
                    .mypage-list__body
                      .mypage-list__text
                        = item.name
                      %div
                        %span.lisiting-item__count
                          %i.fa.fa-heart-o
                          %span
                            0
                        %span.lisiting-item__count
                          %i.fa.fa-comment-o
                          %span
                            0
                        .mypage-item__status#sell-done
                          = item.status
                    %i.fa.fa-chevron-right
          - else
            .tab-content
              %ul.mypage-item__list#mypage-tab__transaction
                %li.mypage-item__listbox#selling-box
                  .mypage-list__body
                    .mypage-list__text
                    %div#non-exist-item
                      取引中の商品はありません
    .mypage-side
      = render "users/mypage/mypage_sidebar"
  %div.morcari-app__banner
    = image_tag("app-banner.jpg", class: "app-image")
  %footer.morcari-footer
    = render 'items/top_footer'

app/views/users/transaction_list.html.haml
.default-container
  %header.morcari-header
    = render 'items/top_header'
  %nav.bread-crumbs
    %ul
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        = link_to "メルカリ", root_path, {itemprop: "url"}
        %i.fa.fa-chevron-right
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        = link_to "マイページ", "/users/#{current_user.id}" , {itemprop: "title"}
        %i.fa.fa-chevron-right
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        %span{itemprop: "title"}
          出品した商品 - 取引中
  %main.mypage-container.clearfix
    .mypage-content
      %section.mypage-tab__container
        %h2.mypage-tab__head#selling-title
          出品した商品
        %ul.mypages-tabs
          %li#selling-tab
            %h3#non-active
              = link_to "出品中", user_my_list_path(@user)
          %li#selling-tab
            %h3
              = link_to "取引中", user_transaction_list_path(@user)
          %li#selling-tab
            %h3#non-active
              = link_to "売却済み", user_sell_end_list_path(@user)
        .tab-content
          %ul.mypage-item__list#mypage-tab__transaction
            %li.mypage-item__listbox#selling-box
              .mypage-list__body
                .mypage-list__text
                %div#non-exist-item
                  取引中の商品はありません
    .mypage-side
      = render "users/mypage/mypage_sidebar"
  %div.morcari-app__banner
    = image_tag("app-banner.jpg", class: "app-image")
  %footer.morcari-footer
    = render 'items/top_footer'