config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }


  root 'items#index'

  get '/users/entrance', to: 'users#entrance', as: 'entrance'

  resources :address, only: [:index, :new, :edit, :update]
  resources :credit, only: [:index, :new, :edit, :update]

  resources :items do
      get 'buy'
      get 'buy_page'
      get 'buy_done'
      get 'buy_done'
      post 'create_review'
  end

  resources :users, only: [:create, :edit, :update, :delete, :show]  do
    get 'complete'
    get 'my_list'
    get 'transaction_list'
    get 'sell_end_list'
    get 'open_trade'
    get 'trading_performance'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one  :area
  has_many :items
  has_many :reviews
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  def after_sign_up_path_for(resource)
    new_address_path
  end

  def after_inactive_sign_up_path_for(resource)
    new_address_path
  end
  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
   @user = current_user
   @items = current_user.items
   @reviews = Review.where(user_id: current_user.id)
  end

  def create
  end

  def edit
  end

  def update
  end

  def entrance
  end

  #初回ユーザー登録
  def complete
   @user = current_user
  end

  def my_list
   @user = current_user
   #出品中itemsのみビューに渡す。
   @items = current_user.items.order("created_at DESC").select {|item| item.status == "出品中"}
  end

  def transaction_list
   @user = current_user
  end

  def sell_end_list
   @user = current_user
   #取引完了itemsのみビューに渡す。
   @items = current_user.items.order("created_at DESC").select {|item| item.status == "取引完了"}
  end

  def open_trade
   @user = current_user
  end

  def trading_performance
   @user = current_user
   @items = Item.all.select {|item| item.buyer_id == current_user.id}
  end

  private

  def user_params
    params.require(:user).permit(
      :nickname,
      :email,
      :last_name,
      :first_name,
      :last_kananame,
      :first_kananame,
      :post_number,
      :city,
      :address,
      :building,
      :phone_number,
      :card_number,
      :expiration_year,
      :expiration_month,
      :security_code,
      :user_photo,
      :total_money,
      :review_id,
      :area_id)
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/mypage/_mypage_main.html.haml
.mypage-content
  %section.mypage-user__icon
    = link_to root_path, {class: "mypage-user__box"} do
      %figure
        = image_tag("member_photo_noimage_thumb.png", width:"60", height:"60")
      %h2.bold
        = current_user.nickname
      .mypage-number
        %div
          評価
          %span.bold
            = @reviews.length
        %div
          出品数
          %span.bold
            = @items.length
  %section.mypage-tab__container
    %ul.mypage-tabs
      %li
        %h3.mypage-tabs__title
          = link_to "お知らせ", root_path
      %li
        %h3.mypage-tabs__title#non-active
          = link_to "やることリスト", root_path
    %ul.mypage-item__list#mypage-tab__notification
      %li
        = link_to root_path, {class: "mypage-item__link"} do
          %figure
            = image_tag("mercari_profile.png", width:"48", height:"48")
          .mypage-item__body
            .mypage-item__text
              事務局から個別メッセージ「毎月1日はメルカリ！月初めは出品も買い物も賑わっています！」
            %time
              %i.fa.fa-clock-o
              %span
                1日前
            %i.fa.fa-chevron-right
      %li.mypage-go__list
        = link_to root_path do
          一覧を見る
  %section#second.mypage-tab__container
    %h2.mypage-tab__head
      購入した商品
    %ul.mypages-tabs
      %li
        %h3
          = link_to "取引中", "user_open_trade_path"
      %li
        %h3#non-active
          = link_to "過去の取引", root_path
    .tab-content
      %ul.mypage-item__list#mypage-tab__transaction
        %li.mypage-item__notfound
          取引中の商品がありません

app/views/users/mypage/_mypage_sidebar.html.haml
%nav.mypage-side__nav
  %ul.mypage-side__list
    %li
      = link_to  "/users/#{current_user.id}" , {class: "mypage-side__item", id: "active"} do
        マイページ
        %i.fa.fa-chevron-right#active
    %li
      = link_to root_path, {class: "mypage-side__item"} do
        お知らせ
        %i.fa.fa-chevron-right
    %li
      = link_to root_path, {class: "mypage-side__item"} do
        やることリスト
        %i.fa.fa-chevron-right
    %li
      = link_to root_path, {class: "mypage-side__item"} do
        いいね一覧
        %i.fa.fa-chevron-right
    %li
      = link_to new_item_path, {class: "mypage-side__item"} do
        出品する
        %i.fa.fa-chevron-right
    %li
      = link_to user_my_list_path(@user), {class: "mypage-side__item"} do
        出品した商品 - 出品中
        %i.fa.fa-chevron-right
    %li
      = link_to user_transaction_list_path(@user), {class: "mypage-side__item"} do
        出品した商品 - 取引中
        %i.fa.fa-chevron-right
    %li
      = link_to user_sell_end_list_path(@user), {class: "mypage-side__item"} do
        出品した商品 - 売却済み
        %i.fa.fa-chevron-right
    %li
      = link_to user_open_trade_path(@user), {class: "mypage-side__item"} do
        購入した商品 - 取引中
        %i.fa.fa-chevron-right
    %li
      = link_to user_trading_performance_path(@user), {class: "mypage-side__item"} do
        購入した商品 - 過去の取引
        %i.fa.fa-chevron-right
    %li
      = link_to root_path, {class: "mypage-side__item"} do
        ニュース一覧
        %i.fa.fa-chevron-right
    %li
      = link_to root_path, {class: "mypage-side__item"} do
        評価一覧
        %i.fa.fa-chevron-right
    %li
      = link_to 'https://www.mercari.com/jp/help_center/', {class: "mypage-side__item"} do
        ガイド
        %i.fa.fa-chevron-right
    %li
      = link_to 'https://www.mercari.com/jp/mypage/support/', {class: "mypage-side__item"} do
        お問い合わせ
        %i.fa.fa-chevron-right
  %h3.mypage-side__head
    売上・ポイント
  %ul.mypage-side__list
    %li
      = link_to root_path, {class: "mypage-side__item"} do
        売上・振込申請
        %i.fa.fa-chevron-right
    %li
      = link_to root_path, {class: "mypage-side__item"} do
        ポイント
        %i.fa.fa-chevron-right
  %h3.mypage-side__head
    設定
  %ul.mypage-side__list
    %li
      = link_to root_path, {class: "mypage-side__item"} do
        プロフィール
        %i.fa.fa-chevron-right
    %li
      = link_to root_path, {class: "mypage-side__item"} do
        住所変更
        %i.fa.fa-chevron-right
    %li
      = link_to root_path, {class: "mypage-side__item"} do
        支払い方法
        %i.fa.fa-chevron-right
    %li
      = link_to root_path, {class: "mypage-side__item"} do
        メール/パスワード
        %i.fa.fa-chevron-right
    %li
      = link_to root_path, {class: "mypage-side__item"} do
        電話番号の確認
        %i.fa.fa-chevron-right
    %li
      = link_to destroy_user_session_path, {class: "mypage-side__item", method: :delete} do
        ログアウト
        %i.fa.fa-chevron-right
%div.morcari-side__banner
  = image_tag("side-banner.jpg", class: "side-image")