config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }


  root 'items#index'

  get '/users/entrance', to: 'users#entrance', as: 'entrance'

  resources :address, only: [:index, :new, :edit, :update]
  resources :credit, only: [:index, :new, :edit, :update]

  resources :items do
      get 'buy'
      get 'buy_page'
      get 'buy_done'
      get 'buy_done'
      post 'create_review'
  end

  resources :users, only: [:create, :edit, :update, :delete, :show]  do
    get 'complete'
    get 'my_list'
    get 'transaction_list'
    get 'sell_end_list'
    get 'open_trade'
    get 'trading_performance'
  end
end

app/controllers/credit_controller.rb
class CreditController < ApplicationController

  def index
  end

  def new
    @user = current_user
  end

  def edit
  end

  def update
    @user = current_user
    if @user.update(credit_params)
      redirect_to user_complete_path(@user)
    end
  end

  private

  def credit_params
    params.require(:user).permit(:card_number,  :expiration_year, :expiration_month,:security_code)
  end
end

app/helpers/credit_helper.rb
module CreditHelper
end

app/views/credit/new.html.haml
%body
  .single-container
    %header.single-header
      %h1
        = link_to root_path, {class: "header-logo"} do
          = image_tag("logo.svg", class: "top-logo")
        %nav.clearfix
          = image_tag("pay.jpg", class: "right-image")
    %main.single-main
      %section.single-contents
        %h2.single-head
          支払い方法
        .single-inner
          .single-content
            = form_for @user, url: credit_path(@user) do |f|
              .form-group
                .form-group__label
                  = f.label :"カード番号"
                %span.form-group__require
                  必須
                .form-group__input
                  = f.text_field :card_number, autofocus: true ,required: "", placeholder: "半角数字のみ", class: "input-default"
                  = image_tag("card_val.jpg", id: "card-image")
              .form-group
                .form-group__label
                  = f.label :"有効期限"
                %span.form-group__require
                  必須
                %br
                .select-wrap
                  = f.select :expiration_month, 1..12, class: "credit-info"
                  %i.fa.fa-chevron-down
                %span.credit-date
                  月
                .select-wrap
                  = f.select :expiration_year, Date.today.year.. 10.years.from_now.year, class: "credit-info"
                  %i.fa.fa-chevron-down
                %span.credit-date
                  年
              .form-group
                .form-group__label
                  = f.label :"セキュリティコード"
                %span.form-group__require
                  必須
                .form-group__input
                  = f.text_field :security_code, required: "", placeholder: "カード背面4桁もしくは3桁の番号",class: "input-default"
              .actions
                = f.submit "次へ進む", class: 'btn-default btn-red'
    = render 'users/footer'