config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }


  root 'items#index'

  get '/users/entrance', to: 'users#entrance', as: 'entrance'

  resources :address, only: [:index, :new, :edit, :update]
  resources :credit, only: [:index, :new, :edit, :update]

  resources :items do
      get 'buy'
      get 'buy_page'
      get 'buy_done'
      get 'buy_done'
      post 'create_review'
  end

  resources :users, only: [:create, :edit, :update, :delete, :show]  do
    get 'complete'
    get 'my_list'
    get 'transaction_list'
    get 'sell_end_list'
    get 'open_trade'
    get 'trading_performance'
  end
end

app/models/item.rb
class Item < ActiveRecord::Base

  has_many :categories
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images
  has_one :area
  has_one :brand
  belongs_to :user

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item_image

  def index
    category_and_item_select
  end

  def category_and_item_select
   #トップビューで表示するカテゴリーを取得する
   @categories = []
   #初期値
   category_num = 1
     while category_num <= 3 do
       @category = Category.find(category_num)
       @categories << @category
       category_num += 1
     end
     @items = []
     #itemに振り分けるカテゴリーを配列から取り出す
     @categories.each do |category|
     @item = Item.where(category_large_id: category.id).select{|item| item.buyer_id == nil}
     @items << @item
     end
  end


  def new
  end

  def create
   @item = Item.new(item_params)
   @item.status = "出品中"
   if @item.save
      if params[:images]
         params[:images].each { |image|
         @item.images.create(image: image)
          }
      end
    redirect_to root_path
   else
    render 'new'
   end
  end


  def show
    @user = current_user
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update

  end


  def destroy
    if @item.user_id == current_user.id
       @item.destroy
       redirect_to 'user_mylist_path'
    end
  end


  def buy_page
    @user = current_user
    @item = Item.find(params[:item_id])
  end

  def buy
    @user = current_user
    @item = Item.find(params[:item_id])
    @item.buyer_id = current_user.id
    @item.status = "取引完了"
    @item.save
    redirect_to item_buy_done_path
  end

  def buy_done
    @user = current_user
    @item = Item.find(params[:item_id])
    #itemの値を先に取り出しておく
      @image = @item.images.first
      @sales_commission = ((@item.price)*0.1).floor
      @profit = (@item.price - @sales_commission)
    @review = Review.new
  end

  def create_review
    @item = Item.find(params[:item_id])
    @review = Review.new(review_params)
    if @review.save
      redirect_to root_path
    end
  end

  private

  def item_params
    params.require(:item).permit(
      :name,
      :description,
      :category_large_id,
      :category_middle_id,
      :category_small_id,
      :size,
      :brand_id,
      :condition,
      :delivery_charge,
      :how_to_delivery,
      :area_id,
      :shipping_dates,
      :price,
      :status,
      images_attributes: [:id, :image]).merge(user_id: current_user.id)
  end

  def image_params
    params.require(:image).permit(
      :image,
      :item_id)
  end

  def review_params
    params.require(:review).permit(
      :evaluation,
      :text,
      :user_id,
      :buyer_id).merge(user_id:@item.user_id , buyer_id: current_user.id)
  end

  def set_item_image
   @item = Item.new
   @item.images.build
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_image_form.html.haml
.view_box
  = f.fields_for :images do |i|
    = i.file_field :image, class: 'file'

app/views/items/_main.html.haml
%div.morcari-main
  .morcari-main__visual
    = image_tag("main-image.jpg", class: "main-image")
  %section.morcari-introduction
    %h2.intro-text
      メルカリは、かんたんに売り買いができて、
      %br
      あんしん・あんぜんなお取引ができる
      %br
      フリマアプリです。
    %ul.intro-ul
      %li
        %h3.intro-title
          %span.intro-num 1
          簡単に出品できる
        = image_tag("intro-num1.jpg", class: "intro-image")
        %p.intro-description
          スマホで写真を撮って
          %br
          特徴を入力するだけで、
          %br
          簡単に出品できます。
      %li
        %h3.intro-title
          %span.intro-num 2
          すぐに購入できる
        = image_tag("intro-num2.jpg", class: "intro-image")
        %p.intro-description
          ボタン1つで購入。
          %br
          あとは出品者からの
          %br
          発送を待つだけです。
      %li
        %h3.intro-title
          %span.intro-num 3
          商品がたくさん
        = image_tag("intro-num3.jpg", class: "intro-image")
        %p.intro-description
          毎日数十万品以上の新商品が
          %br
          出品されるので、欲しいものが
          %br
          きっと見つかります。
  %section.middle-introduction
    = image_tag("middle-image.jpg", class: "middle-image")
  %section.morcari-features
    %h2.morcari-features__text
      メルカリの特徴
    .morcari-features__container
      .morcari-features__item
        %div.features-image
          = image_tag("item1.svg", class: "item-image")
        %h3
          3分でかんたん売り買い
        %p
          着なくなった服や小物、本な
          %br
          どを売ってみよう！ お小遣い
          %br
          稼ぎに使えます
      .morcari-features__item
        %div.features-image
          = image_tag("item2.svg", class: "item-image")
        %h3
          あんしんの売買システム
        %p
          お金のやりとりはメルカリ
          %br
          が仲介し、商品が届いてか
          %br
          ら出品者に振り込まれるので
          %br
          安心です
      .morcari-features__item
        %div.features-image
          = image_tag("item3.svg", class: "item-image")
        %h3
          多彩な支払い方法
        %p
          購入した商品のお支払いは、クレジットカード/ポイント/売上金からどうぞ！
      .morcari-features__item
        %div.features-image
          = image_tag("item4.svg", class: "item-image")
        %h3
          出品はもちろん無料
        %p
          その他、会員登録料・月会費・カード手数料は一切かかりません
  %section.morcari__template
    %h2.pickup-head
      ピックアップカテゴリー
    %section.items-box__container
      %h3.items-box__text
        = @categories[0].name
      .item-box__content
        - @items[0][0..3].each do |item|
          %section.items-box
            = link_to "/items/#{item.id}",class: "mypage-item__link", id: "link-box" do
              %figure.items-box__photo
                = image_tag(item.images.first.image.url, class: "items-image")
              .items-box__body
                %h3.items-box__name
                  = item.name
                .items-box__num
                  .items-box__price
                    = "¥#{item.price}"
                  %p.items-box__tax
                    (税 ¥ 0)
    %section#other-content.items-box__container
      %h3.items-box__text
        = @categories[1].name
      .item-box__content
        - @items[1][0..3].each do |item|
          %section#left-content.items-box
            = link_to "/items/#{item.id}",class: "mypage-item__link", id: "link-box" do
              %figure.items-box__photo
                = image_tag(item.images.first.image.url, class: "items-image")
              .items-box__body
                %h3.items-box__name
                  = item.name
                .items-box__num
                  .items-box__price
                    = "¥#{item.price}"
                  %p.items-box__tax
                    (税 ¥ 0)
    %section#other-content.items-box__container
      %h3.items-box__text
        = @categories[2].name
      .item-box__content
        - @items[2][0..3].each do |item|
          %section#left-content.items-box
            = link_to "/items/#{item.id}",class: "mypage-item__link", id: "link-box" do
              %figure.items-box__photo
                = image_tag(item.images.first.image.url, class: "items-image")
              .items-box__body
                %h3.items-box__name
                  = item.name
                .items-box__num
                  .items-box__price
                    = "¥#{item.price}"
                  %p.items-box__tax
                    (税 ¥ 0)
  %section.morcari__template#morcari-brand
    %h2.pickup-head
      ピックアップブランド
    %section.items-box__container
      %h3#brand-title.items-box__text
        ヴィトン
      .item-box__content
        %section#left-content.items-box
          %a{ href: 'https://www.mercari.com/jp/'}
            %figure.items-box__photo
              = image_tag("sample.jpg", class: "items-image")
            .items-box__body
              %h3.items-box__name
                ルイヴィトン
              .items-box__num
                .items-box__price
                  ¥ 800
                %p.items-box__tax
                  (税 ¥ 0)
        %section.items-box
          %a{ href: 'https://www.mercari.com/jp/'}
            %figure.items-box__photo
              = image_tag("sample.jpg", class: "items-image")
            .items-box__body
              %h3.items-box__name
                ルイヴィトン
              .items-box__num
                .items-box__price
                  ¥ 800
                %p.items-box__tax
                  (税 ¥ 0)
        %section.items-box
          %a{ href: 'https://www.mercari.com/jp/'}
            %figure.items-box__photo
              = image_tag("sample.jpg", class: "items-image")
            .items-box__body
              %h3.items-box__name
                ルイヴィトン
              .items-box__num
                .items-box__price
                  ¥ 800
                %p.items-box__tax
                  (税 ¥ 0)
        %section.items-box
          %a{ href: 'https://www.mercari.com/jp/'}
            %figure.items-box__photo
              = image_tag("sample.jpg", class: "items-image")
            .items-box__body
              %h3.items-box__name
                ルイヴィトン
              .items-box__num
                .items-box__price
                  ¥ 800
                %p.items-box__tax
                  (税 ¥ 0)
    .non
    %section.items-box__container
      %h3#brand-title.items-box__text
        ヴィトン
      .item-box__content
        %section#left-content.items-box
          %a{ href: 'https://www.mercari.com/jp/'}
            %figure.items-box__photo
              = image_tag("sample.jpg", class: "items-image")
            .items-box__body
              %h3.items-box__name
                ルイヴィトン
              .items-box__num
                .items-box__price
                  ¥ 800
                %p.items-box__tax
                  (税 ¥ 0)
        %section.items-box
          %a{ href: 'https://www.mercari.com/jp/'}
            %figure.items-box__photo
              = image_tag("sample.jpg", class: "items-image")
            .items-box__body
              %h3.items-box__name
                ルイヴィトン
              .items-box__num
                .items-box__price
                  ¥ 800
                %p.items-box__tax
                  (税 ¥ 0)
        %section.items-box
          %a{ href: 'https://www.mercari.com/jp/'}
            %figure.items-box__photo
              = image_tag("sample.jpg", class: "items-image")
            .items-box__body
              %h3.items-box__name
                ルイヴィトン
              .items-box__num
                .items-box__price
                  ¥ 800
                %p.items-box__tax
                  (税 ¥ 0)
        %section.items-box
          %a{ href: 'https://www.mercari.com/jp/'}
            %figure.items-box__photo
              = image_tag("sample.jpg", class: "items-image")
            .items-box__body
              %h3.items-box__name
                ルイヴィトン
              .items-box__num
                .items-box__price
                  ¥ 800
                %p.items-box__tax
                  (税 ¥ 0)

app/views/items/_top_footer.html.haml
%nav
  %ul
    %li.footer-cell
      %h2.footer-head
        メルカリについて
      %ul
        %li
          %a{ href: 'https://www.mercari.com/jp/privacy/'}
            プライバシーポリシー
        %li
          %a{ href: 'https://www.mercari.com/jp/tos/'}
            利用規約
        %li
          %a{ href: 'https://www.mercari.com/jp/about/'}
            会社概要(運営会社)
        %li
          %a{ href: 'https://www.mercari.com/jp/tokutei/'}
            特定商取引に関する表記
        %li
          %a{ href: 'https://www.mercari.com/jp/safe/compliance/'}
            法令遵守と犯罪抑止のために
        %li
          %a{ href: 'https://www.mercari.com/jp/jobs/'}
            採用情報
        %li
          %a{ href: 'https://www.mercariatte.com/jp/'}
            メルカリアッテ
    %li.footer-cell
      %h2.footer-head
        メルカリを見る
      %ul
        %li
          %a{ href: 'https://www.mercari.com/jp/privacy/'}
            カテゴリー一覧
        %li
          %a{ href: 'https://www.mercari.com/jp/tos/'}
            ブランド一覧
        %li
          %a{ href: 'https://www.mercari.com/jp/about/'}
            出品地域一覧
        %li
          %a{ href: 'https://www.mercari.com/jp/tokutei/'}
            公式Twitter
        %li
          %a{ href: 'https://www.mercari.com/jp/safe/compliance/'}
            公式フェイスブック
    %li.footer-cell
      %h2.footer-head
        ヘルプ&ガイド
      %ul
        %li
          %a{ href: 'https://www.mercari.com/jp/privacy/'}
            メルカリロゴ利用ガイドライン
        %li
          %a{ href: 'https://www.mercari.com/jp/tos/'}
            お知らせ
        %li
          %a{ href: 'https://www.mercari.com/jp/about/'}
            らくらくメルカリ便とは
        %li
          %a{ href: 'https://www.mercari.com/jp/tokutei/'}
            ゆうゆうメルカリ便とは
        %li
          %a{ href: 'https://www.mercari.com/jp/safe/compliance/'}
            大型らくらくメルカリ便とは
        %li
          %a{ href: 'https://www.mercari.com/jp/jobs/'}
            車体取引ガイド
        %li
          %a{ href: 'https://www.mercariatte.com/jp/'}
            返品・返金ポリシー
        %li
          %a{ href: 'https://www.mercariatte.com/jp/'}
            メルカリあんしん・あんぜん宣言！
        %li
          %a{ href: 'https://www.mercariatte.com/jp/'}
            メルカリボックス
    %li.footer-cell
      %h2.footer-head
        国
      %ul
        %li
          %a{ href: 'https://www.mercari.com/jp/privacy/'}
            United State
        %li
          %a{ href: 'https://www.mercari.com/jp/tos/'}
            United Kingdam
        %li
          %a{ href: 'https://www.mercari.com/jp/about/'}
            日本
= link_to root_path, {class: "footer-logo"} do
  = image_tag("logo-white.svg", class: "logo-image")
%p.footer-copyright
  © 2017 Mercari
= link_to new_item_path, {class: "footer-sell__btn"} do
  .footer-sell__title
    出品
  %i.fa.fa-camera

app/views/items/_top_header.html.haml
.morcari-header__inner
  .clearfix
    %h1.morcari-header__left
      = link_to root_path, {class: "header-logo"} do
        = image_tag("logo.svg", class: "top-logo")
    %form{action: "/", method: "post", class: "morcari-header__right"}
      %input{name: "title", size: "130", placeholder: "キーワードから探す", class: "morcari-search"}
  .morcari-header__navibox.clearfix
    .header-navibox__left
      %ul.header-nav
        %li
          %h2.header-nav__text#first-nav
            カテゴリー
        %li
          %h2.header-nav__text
            ブランド
    .header-navibox__right
      - if user_signed_in?
        %ul.user-nav
          %li
            = link_to "/users/#{current_user.id}" do
              = image_tag("member_photo_noimage_thumb.png")
              マイページ
          %li
            = link_to "users/entrance" do
              %i.fa.fa-bell
              お知らせ
          %li
            = link_to "users/entrance" do
              %i.fa.fa-check
              やることリスト
      - else
        %ul.user-nav
          %li
            = link_to "ログイン",new_user_session_path, class: "btn-red"
          %li
            = link_to "新規会員登録",entrance_path, class: "btn-blue"

app/views/items/buy_done.html.haml
.default-container
  %header.morcari-header
    = render 'items/top_header'
  %nav.bread-crumbs
    %ul
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        = link_to "メルカリ", root_path, {itemprop: "url"}
        %i.fa.fa-chevron-right
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        = link_to "マイページ", "/users/current_user.id" , {itemprop: "title"}
        %i.fa.fa-chevron-right
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        = link_to "出品した商品 - 出品中", "/users/#{@user.id}/mylist" , {itemprop: "title"}
        %i.fa.fa-chevron-right
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        = link_to "出品商品画面", "/users/#{@user.id}/mylist" , {itemprop: "title"}
        %i.fa.fa-chevron-right
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        %span{itemprop: "title"}
          購入完了画面
  %main.transact-container.clearfix
    = form_for @review, :url => {:action => :create_review} do |f|
      .transact-right__content
        %h2.right-content__head
          取引画面
        .transact-attention
          %h3
            %i.fa.fa-truck
            %span
              らくらくメルカリ便で発送する
          %p
            商品が購入され支払いされました。発送してください。らくらくメルカリ便では、コンビニへの持ち込み、ヤマト営業所への持ち込み、またはご自宅への集荷依頼を選択できます。
        %ul.transact-guide
          %li
            = link_to "https://www.mercari.com/jp/help_center/article/63/" do
              %span
                商品が売れた後の流れ
              %i.fa.fa-chevron-right
          %li
            = link_to "https://www.mercari.com/jp/help_center/category/2/" do
              %span
                出品者のよくある質問
              %i.fa.fa-chevron-right
          %li
            = link_to "https://www.mercari.com/jp/help_center/category/13/" do
              %span
                らくらくメルカリ便とは？
              %i.fa.fa-chevron-right
        .transact-button
          .btn-default.btn-red
            コンビニから発送
        .transact-button
          .btn-default.btn-red
            ヤマトの営業所へ持ち込んで発送
        .transact-button
          .btn-default.btn-red
            ヤマトの集荷サービスを利用して発送
        %p.transact-shipping__fee
          集荷料¥30が追加されます
        .transact-button
          .btn-default.btn-radius
            らくらくメルカリ便を使わない
        .transact-wordings
          %h4
            ※配送のお問い合わせは
            = link_to "こちら", "https://www.mercari.com/jp/mypage/support/",target: "_blank"
            よりお願いします。
          %p
            (ヤマト運輸への直接のお問い合わせ、ご回答等はできませんのでご了承ください)
        .transact-attention#review-container
          %h3
            %i.fa.fa-check
            %span
              評価をしてください
          %p
            商品の発送/受取が完了しました。
            取引相手の評価を行なって、取引を完了してください。
        .transact-review
          評価
        .transact-review__checkbox
          %label
            %input{type: "checkbox",class: "checkbox-input"}
            %span.checkbox-parts
              %p
                取引内容を確認しました
        .transact-review__select
          .review-select__icon
            %i.fa.fa-smile-o
            //良い
            %i.fa.fa-meh-o
            //普通
            %i.fa.fa-frown-o
            //悪い
          .review-select__evaluation
            .review-comment__good
              良い
            .review-comment__normal
              普通
            .review-comment__bad
              悪い
          .review-select__button
            %label
              = f.radio_button :evaluation,"good", class: "radio-input"
              %span.radio-parts
            %label
              = f.radio_button :evaluation,"normal", class: "radio-input"
              %span.radio-parts
            %label
              = f.radio_button :evaluation,"bad", class: "radio-input"
              %span.radio-parts
          .review-write__comment
            .review-comment__container
              .review-comment__content
                %p
                  評価のコメントを記入しましょう
                = f.text_area :text, rows: "2", placeholder: "このコメントは、取引完了後に評価一覧で公開されます。商品に問題がある場合などは、評価をせずに取引メッセージで伝えましょう。", class: 'review-textarea'
                = f.submit "評価を投稿する", class: 'btn-default btn-red message-btn'
    .transact-left__content
      %nav.transact-left__nav
        %h3.transact-left__head
          取引情報
        .transact-info__inner
          %ul.transact-info__table
            %li.transact-info__list
              %span.transact-info__title
                商品
              %ul
                %li.transact-info__detail
                  = @item.name
                  //= image_tag @image.url
            %li.transact-info__list#list-gray
              %span.transact-info__title
                送料
              %ul
                %li.transact-info__detail
                  = @item.delivery_charge
            %li.transact-info__list
              %span.transact-info__title
                販売手数料
              %ul
                %li.transact-info__detail
                  = "¥#{@sales_commission}"
            %li.transact-info__list#list-gray
              %span.transact-info__title
                販売利益
              %ul
                %li.transact-info__detail
                  = "¥#{@profit}"
            %li.transact-info__list
              %span.transact-info__title
                購入日時
              %ul
                %li.transact-info__detail
                  = @item.updated_at
            %li.transact-info__list#list-gray
              %span.transact-info__title
                商品ID
              %ul
                %li.transact-info__detail
                  = @item.id
      %section.side-user__info
        %h3.side-user__head
          購入者情報
        .side-user__inner
          = link_to root_path, {class: "mypage-side__item"} do
            %figure
              %div
                = image_tag("member_photo_noimage_thumb.png")
              %figcaption
                .transact-user__name
                  もりもりた
              %i.fa.fa-chevron-right
      %div.morcari-side__banner
        = image_tag("side-banner.jpg", class: "side-image")
  %div.morcari-app__banner
    = image_tag("app-banner.jpg", class: "app-image")
  %footer.morcari-footer
    = render 'items/top_footer'

app/views/items/buy_page.html.haml
%body
  .single-container
    %header.single-header
      %h1
        = link_to root_path, {class: "header-logo"} do
          = image_tag("logo.svg", class: "top-logo")
    %main.single-main
      %section.single-contents
        %h2.single-head
          購入を確定しますか？
        .single-inner
          .buy-content
            %h3.buy-item__image
              = image_tag(@item.images.first.image.url, class: "item-image")
            %h3.buy-item__name
              = @item.name
            %div.buy-item__menu
              %p.buy-price
                = "¥#{@item.price}"
                %span
                  送料込み
              %ul.buy-accordion
                %li.buy-accordion__parent
                  .buy-accordion__toggle
                    売上金はありません
              %ul.buy-accordion
                %li.buy-accordion__parent
                  .buy-accordion__toggle
                    ポイントはありません
              %ul.buy-price__table
                %li
                  .buy-price__payment
                    支払い金額
                  .buy-price__money
                    = "¥#{@item.price}"
              = link_to "購入する",  "/items/#{@item.id}/buy",class: "btn-red btn-default"
          %section.buy-content
            .buy-content__inner
              %h3
                配達先
              %address.buy-user__info
                = "〒#{@user.post_number}"
                = @user.city
          %section.buy-content
            .buy-content__inner
              %h3
                支払い方法
              %credit.buy-user__info
                = "************#{@user.card_number}"
                = @user.city
    = render 'users/footer'

app/views/items/index.html.haml
.default-container
  %header.morcari-header
    = render 'top_header'
  %div.morcari-campaign__banner
    = image_tag("campaign-banner.jpg", class: "banner-image")
  %div.morcari-main
    = render 'main'
  %div.morcari-app__banner
    = image_tag("app-banner.jpg", class: "app-image")
  %footer.morcari-footer
    = render 'top_footer'

app/views/items/show.html.haml
.default-container
  %header.morcari-header
    = render 'items/top_header'
  %nav.bread-crumbs
    %ul
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        = link_to "メルカリ", root_path, {itemprop: "url"}
        %i.fa.fa-chevron-right
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        = link_to "マイページ", "/users/current_user.id" , {itemprop: "title"}
        %i.fa.fa-chevron-right
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        = link_to "出品した商品 - 出品中", "/users/#{@user.id}/mylist" , {itemprop: "title"}
        %i.fa.fa-chevron-right
      %li{itemscope: "", itemtype: "http://data-vocabulary.org/Breadcrumb"}
        %span{itemprop: "title"}
          出品商品画面
  %main.mypage-container.clearfix
    .item-box
      %section.item-box__container
        %h2.item-box__name
          = @item.name
        .item-main__content
          .item-image
            .item-carousel
              .item-carousel__box
                .item-carousel__stage
                  - @item.images.each do |image|
                    .item-carousel__list
                      .item-carousel__inner
                        = image_tag image.image.url
            .item-disable__menu
              .item-disable__prev
                prev
              .item-disable__next
                next
            .item-list__images
              - @item.images.each_with_index do |image, i|
                %span
                .item-list__image{data: { id: i}}
                  = image_tag image.image.url
          %table.item-main__detail
            %tbody
              %tr
                %th
                  出品者
                %td
                  = @item.user.nickname
              %tr
                %th
                  カテゴリー
                %td
                  = @item.category_large_id
                  = @item.category_middle_id
                  = @item.category_small_id
              %tr
                %th
                  ブランド
                %td
                  = @item.brand_id
              %tr
                %th
                  商品のサイズ
                %td
                  = @item.size
              %tr
                %th
                  商品の状態
                %td
                  = @item.condition
              %tr
                %th
                  配送料の負担
                %td
                  = @item.delivery_charge
              %tr
                %th
                  配送の方法
                %td
                  = @item.how_to_delivery
              %tr
                %th
                  配送元地域
                %td
                  = @item.area_id
              %tr
                %th
                  発送日の目安
                %td
                  = @item.shipping_dates
        .item-main__pricebox
          %span.item-main__price
            = "¥#{@item.price}"
          %span
            (税  ¥0)
          %span.item-main__shipfee
            送料込み
        - if current_user.id != @item.user_id
          = link_to "購入", "/items/#{@item.id}/buy_page", class: 'btn-default btn-red item-buy'
        .item-main__description
          = @item.description
      - if current_user.id == @item.user_id
        .item-change__box
          = link_to "商品の編集", "/items/#{@item.id}/edit", class: 'btn-default btn-red'
          %p.item-text__center
            or
          = link_to "出品を一旦停止する",root_path, class: 'btn-default btn-gray'
          = link_to "この商品を削除する","/items/#{@item.id}",method: :delete, class: 'btn-default btn-gray'
      .item-detail__message
        .item-message__container
          .item-message__content
            %p
              相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
            %textarea
            = link_to "コメントする",root_path, class: 'btn-default btn-red message-btn'
    .mypage-side
      %div.morcari-side__banner
        = image_tag("side-banner.jpg", class: "side-image")
  %div.morcari-app__banner
    = image_tag("app-banner.jpg", class: "app-image")
  %footer.morcari-footer
    = render 'items/top_footer'